# Generated by Django 5.2.1 on 2025-05-29 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('school_student', models.BooleanField(default=False)),
                ('email_token', models.UUIDField(default=uuid.uuid4)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
