# Generated by Django 5.2.1 on 2025-06-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myedu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars/'),
        ),
    ]
