# Generated by Django 5.1.7 on 2025-05-16 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myedu', '0002_emailverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EmailVerify',
        ),
    ]
