# Generated by Django 5.2.1 on 2025-06-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myedu', '0002_student_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
    ]
