# Generated by Django 5.2.1 on 2025-06-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myedu', '0003_remove_student_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
